/*! jquery.cookie.js */
jQuery.cookie=function(name,value,options){if(typeof value!='undefined'){options=options||{};if(value===null){value='';options.expires=-1}var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000))}else{date=options.expires}expires='; expires='+date.toUTCString()}var path=options.path?'; path='+(options.path):'';var domain=options.domain?'; domain='+(options.domain):'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('')}else{var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break}}}return cookieValue}};var BP=BP||{};BP.DomElementCache={cache:[],set:function(selector,domElement){var returnvalue=false;if(this.hasOwnProperty(selector)){returnvalue=true;}
this.cache[selector]=domElement;return returnvalue;},get:function(selector){if(this.cache[selector]===undefined){this.cache[selector]=$(selector);}
return this.cache[selector];}};$(document).ready(function(){BP.DomElementCache.set('window',$(window));BP.DomElementCache.set('document',$(document));});var BP=BP||{};BP.Utils={};BP.Utils.updateUrlAndTitleInBrowserAddressbar=function(newTitle,link){"use strict";var TITLE_SEPARATOR=':',currentTitle,currentTitlePrefix;if(newTitle.indexOf(TITLE_SEPARATOR)<=0){currentTitle=document.title;currentTitlePrefix=currentTitle.substr(0,currentTitle.indexOf(TITLE_SEPARATOR));if(currentTitlePrefix!==''){newTitle=currentTitlePrefix+newTitle;}}
if(history&&history.replaceState){history.replaceState(null,newTitle,link);}};BP.Utils.getWindowScrollingPositionY=function(){"use strict";return window.pageYOffset||document.body.scrollTop||document.documentElement.scrollTop||0;};BP.Utils.trackLinkInGoogleAnalytics=function(linkTarget){"use strict";var _gaq=window._gaq||[];_gaq.push(['_trackPageview',linkTarget]);};BP.Utils.getIntersectionOfArrays=function(arrayOne,arrayTwo){"use strict";var intersectionArray=[],arrayOneLength=arrayOne.length,arrayTwoLength=arrayTwo.length,i,j;for(i=0;i<arrayOneLength;i++){for(j=0;j<arrayTwoLength;j++){if(arrayOne[i]===arrayTwo[j]){intersectionArray.push(arrayOne[i]);break;}}}
return intersectionArray;};BP.Utils.deviceIsSmartphone=function(){"use strict";if(/Android|webOS|iPhone|iPad|iPod|iOS|BlackBerry/i.test(navigator.userAgent)){return true;}
return false;};BP.Utils.renderTemplate=function(template,values){"use strict";for(var p in values)
template=template.replace(new RegExp('{'+p+'}','g'),values[p]);return template;};BP.Utils.identifyGivenParameter=function(parameter){"use strict";parameter=parameter.replace(/[\[]/,'\\\[').replace(/[\]]/,'\\\]');var regexSearch='[\\?&]'+parameter+'=([^&#]*)';var regex=new RegExp(regexSearch);var highlights=regex.exec(window.location.href);if(highlights==null){return false;}
else{return highlights[1];}};Array.prototype.max=function(){"use strict";return Math.max.apply(Math,this);};Array.prototype.min=function(){"use strict";return Math.min.apply(Math,this);};window.onerror=function(message,file,line){"use strict";if(message==='QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.'){return;}
if(window._gaq){var errorMsg=file+':'+line+' '+message;window._gaq.push(['_trackEvent','Error','JS Error',errorMsg]);}};$(document).ajaxError(function(e,xhr,settings){"use strict";if(window._gaq){var errorMsg=settings.url+' : '+xhr.status+' '+xhr.responseText;window._gaq.push(['_trackEvent','Error','jQuery Ajax Error',errorMsg]);}});$.fn.datepicker=function(){return false;};jQuery.easing['jswing']=jQuery.easing['swing'];jQuery.extend(jQuery.easing,{def:'easeOutQuad',swing:function(x,t,b,c,d){return jQuery.easing[jQuery.easing.def](x,t,b,c,d);},easeInQuad:function(x,t,b,c,d){return c*(t/=d)*t+b;},easeOutQuad:function(x,t,b,c,d){return-c*(t/=d)*(t-2)+b;},easeInOutQuad:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t+b;return-c/2*((--t)*(t-2)-1)+b;},easeInCubic:function(x,t,b,c,d){return c*(t/=d)*t*t+b;},easeOutCubic:function(x,t,b,c,d){return c*((t=t/d-1)*t*t+1)+b;},easeInOutCubic:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t+b;return c/2*((t-=2)*t*t+2)+b;},easeInQuart:function(x,t,b,c,d){return c*(t/=d)*t*t*t+b;},easeOutQuart:function(x,t,b,c,d){return-c*((t=t/d-1)*t*t*t-1)+b;},easeInOutQuart:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t+b;return-c/2*((t-=2)*t*t*t-2)+b;},easeInQuint:function(x,t,b,c,d){return c*(t/=d)*t*t*t*t+b;},easeOutQuint:function(x,t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;},easeInOutQuint:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t*t+b;return c/2*((t-=2)*t*t*t*t+2)+b;},easeInSine:function(x,t,b,c,d){return-c*Math.cos(t/d*(Math.PI/2))+c+b;},easeOutSine:function(x,t,b,c,d){return c*Math.sin(t/d*(Math.PI/2))+b;},easeInOutSine:function(x,t,b,c,d){return-c/2*(Math.cos(Math.PI*t/d)-1)+b;},easeInExpo:function(x,t,b,c,d){return(t==0)?b:c*Math.pow(2,10*(t/d-1))+b;},easeOutExpo:function(x,t,b,c,d){return(t==d)?b+c:c*(-Math.pow(2,-10*t/d)+1)+b;},easeInOutExpo:function(x,t,b,c,d){if(t==0)return b;if(t==d)return b+c;if((t/=d/2)<1)return c/2*Math.pow(2,10*(t-1))+b;return c/2*(-Math.pow(2,-10*--t)+2)+b;},easeInCirc:function(x,t,b,c,d){return-c*(Math.sqrt(1-(t/=d)*t)-1)+b;},easeOutCirc:function(x,t,b,c,d){return c*Math.sqrt(1-(t=t/d-1)*t)+b;},easeInOutCirc:function(x,t,b,c,d){if((t/=d/2)<1)return-c/2*(Math.sqrt(1-t*t)-1)+b;return c/2*(Math.sqrt(1-(t-=2)*t)+1)+b;},easeInElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},easeOutElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d)==1)return b+c;if(!p)p=d*.3;if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);return a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b;},easeInOutElastic:function(x,t,b,c,d){var s=1.70158;var p=0;var a=c;if(t==0)return b;if((t/=d/2)==2)return b+c;if(!p)p=d*(.3*1.5);if(a<Math.abs(c)){a=c;var s=p/4;}
else var s=p/(2*Math.PI)*Math.asin(c/a);if(t<1)return-.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*.5+c+b;},easeInBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b;},easeOutBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},easeInOutBack:function(x,t,b,c,d,s){if(s==undefined)s=1.70158;if((t/=d/2)<1)return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},easeInBounce:function(x,t,b,c,d){return c-jQuery.easing.easeOutBounce(x,d-t,0,c,d)+b;},easeOutBounce:function(x,t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+.75)+b;}else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+.9375)+b;}else{return c*(7.5625*(t-=(2.625/2.75))*t+.984375)+b;}},easeInOutBounce:function(x,t,b,c,d){if(t<d/2)return jQuery.easing.easeInBounce(x,t*2,0,c,d)*.5+b;return jQuery.easing.easeOutBounce(x,t*2-d,0,c,d)*.5+c*.5+b;}});jQuery.extend(jQuery.easing,{easeIn:function(x,t,b,c,d){return jQuery.easing.easeInQuad(x,t,b,c,d);},easeOut:function(x,t,b,c,d){return jQuery.easing.easeOutQuad(x,t,b,c,d);},easeInOut:function(x,t,b,c,d){return jQuery.easing.easeInOutQuad(x,t,b,c,d);},expoin:function(x,t,b,c,d){return jQuery.easing.easeInExpo(x,t,b,c,d);},expoout:function(x,t,b,c,d){return jQuery.easing.easeOutExpo(x,t,b,c,d);},expoinout:function(x,t,b,c,d){return jQuery.easing.easeInOutExpo(x,t,b,c,d);},bouncein:function(x,t,b,c,d){return jQuery.easing.easeInBounce(x,t,b,c,d);},bounceout:function(x,t,b,c,d){return jQuery.easing.easeOutBounce(x,t,b,c,d);},bounceinout:function(x,t,b,c,d){return jQuery.easing.easeInOutBounce(x,t,b,c,d);},elasin:function(x,t,b,c,d){return jQuery.easing.easeInElastic(x,t,b,c,d);},elasout:function(x,t,b,c,d){return jQuery.easing.easeOutElastic(x,t,b,c,d);},elasinout:function(x,t,b,c,d){return jQuery.easing.easeInOutElastic(x,t,b,c,d);},backin:function(x,t,b,c,d){return jQuery.easing.easeInBack(x,t,b,c,d);},backout:function(x,t,b,c,d){return jQuery.easing.easeOutBack(x,t,b,c,d);},backinout:function(x,t,b,c,d){return jQuery.easing.easeInOutBack(x,t,b,c,d);}});$(document).ready(function(){"use strict";if(BP!==undefined&&BP.hasOwnProperty('HeaderMessage')){if(typeof BP.HeaderMessage==='object'&&BP.HeaderMessage.hasOwnProperty('message')){BP.DomElementCache.get('body').addClass('hasMessage').prepend('<div id="jsHeaderMessage" class="container_100 message"><p>'+BP.HeaderMessage.message+'</p></div>');if(BP.HeaderMessage.hasOwnProperty('color')&&BP.HeaderMessage.color!==''){BP.DomElementCache.get('#jsHeaderMessage').addClass(BP.HeaderMessage.color);}
$(window).bind('load resize',function(){var bgpos=(($(window).width()-2500)/2)-23;BP.DomElementCache.get('body').css({'background-position':bgpos+'px top'});});}}});$(document).ready(function(){"use strict";if($("#dropnavi").length>0){var megadropdownMenu=new Menu(0.3,'linear','linear',5050,'easeInOutQuart','dropnavi');}
if($("body.index").length>0){var homepageTeaserMenu=new Menu(0.3,'linear','linear',5050,'easeInOutQuart','tab_slider');}});function Menu(fadeStrength,fadeInEffect,fadeOutEffect,fadeRelation,slideEffect,slider){"use strict";var that=this;this.fadeStrength=fadeStrength;this.slideEffect=slideEffect;this.fadeInEffect=fadeInEffect;this.fadeOutEffect=fadeOutEffect;this.fadeRelation=fadeRelation;this.slider=slider;this.imagesInDropnaviAlreadyLoaded=false;$('.hasOverview a').click(function(e){e.preventDefault();});this.actualPosition=0;this.actualMargin=0;if(this.slider==='dropnavi'){this.$itemOverview=$('#item-overview');this.$itemArray=$('#item-overview > .item');this.$navElements=$('.first-level .hasOverview');this.sliderWidth=$('.main-navigation').width();this.$lastElement=null;this.$itemOverviewWidth=this.$itemArray.length*this.sliderWidth;this.$itemOverview.width(this.$itemOverviewWidth);this.$navElements.click(function(e){that.menuController(e,that);});}
else if(this.slider==='tab_slider'){this.tab_slider=$('#tab_slider');this.$itemOverview=$('#tab_slider_wrapper');this.$itemArray=$('#tab_slider_wrapper > .item');this.$navElements=$('#tab_slider li');this.sliderWidth=$('#tab_slider').width();this.$lastElement=null;this.$itemOverviewWidth=this.$itemArray.length*this.sliderWidth;this.$itemOverview.width(this.$itemOverviewWidth);this.autoSliderCounter=0;this.$currentNavEventListener=$($('.tabnav a')[this.autoSliderCounter]);this.autoSliderStop=false;this.autoSlider(that);this.tab_slider.mouseenter(function(e){that.stopAutoCycle(e,that);});this.tab_slider.mouseleave(function(e){that.startAutoCycle(e,that);});this.$navElements.click(function(e){that.tab_slide_controller(e,that);});}else{return;}}
Menu.prototype.stopAutoCycle=function(e,that){"use strict";that.autoSliderStop=true;};Menu.prototype.startAutoCycle=function(e,that){"use strict";that.autoSliderStop=false;};Menu.prototype.autoSlider=function(that){"use strict";that.$currentNavEventListener=$($('.tabnav a')[that.autoSliderCounter]);if(that.autoSliderStop===false){if(that.$lastElement!==null){that.$lastElement.removeClass('slide_active');}
if(that.autoSliderCounter<that.$itemArray.length-1){that.autoSliderCounter++;}else{that.autoSliderCounter=0;}
that.$lastElement=that.$currentNavEventListener.parent();that.$lastElement.addClass('slide_active');that.animateSlide(that.$currentNavEventListener);}
setTimeout(function(){that.autoSlider(that);},8000);};Menu.prototype.tab_slide_controller=function(e,that){"use strict";that.$currentNavEventListener=$(e.target);if(that.$lastElement!==null){that.$lastElement.removeClass('slide_active');}
if(!that.$currentNavEventListener.parent().hasClass('slide_active')){that.$lastElement=that.$currentNavEventListener.parent();that.$lastElement.addClass('slide_active');that.animateSlide(that.$currentNavEventListener);}else{return;}};Menu.prototype.menuController=function(e,that){"use strict";var $clickedElement=$(e.target);if(!this.imagesInDropnaviAlreadyLoaded){this.imagesInDropnaviAlreadyLoaded=true;var allImagesInMegaDropnav=$('#item-overview').find('img');var allImagesInMegaDropnavLength=allImagesInMegaDropnav.length;for(var i=0;i<allImagesInMegaDropnavLength;i++){var currentImage=$(allImagesInMegaDropnav[i]);var currentImageUrl=currentImage.attr('data-imageToLoad');if(currentImageUrl!==''){currentImage.attr('src',currentImageUrl);}}}
if($clickedElement.parent().hasClass('slide_active')){that.$itemOverview.slideUp();$clickedElement.parent().removeClass('slide_active');}
else{if(that.$lastElement!==null){that.$lastElement.removeClass('slide_active');}
that.$lastElement=$(e.target).parent();that.$lastElement.addClass('slide_active');if(that.$itemOverview.css('display')==='block'){that.animateSlide($clickedElement);}
else{that.actualPosition=$(that.$navElements).index($clickedElement.parent());var firstMarginleft=that.actualPosition*that.sliderWidth;that.$itemOverview.css('marginLeft',-firstMarginleft);that.actualMargin=-firstMarginleft;that.$itemOverview.slideDown();}}};Menu.prototype.animateSlide=function($clickedElement){"use strict";var newPosition=$(this.$navElements).index($clickedElement.parent());var that=this;var distance=this.actualPosition-newPosition;if(distance===0){return;}
else{var timing=0;var fadePart1;var fadePart2;if(distance<=2&&distance>=-2){timing=500;}else{timing=1000;}
if(this.fadeRelation==="5050"){fadePart1=timing/100*50;fadePart2=timing/100*50;}
else{fadePart1=timing/100*20;fadePart2=timing/100*80;}
var toSlideDistance=this.sliderWidth*distance;this.actualMargin=this.actualMargin+toSlideDistance;this.$itemOverview.animate({opacity:this.fadeStrength},{duration:fadePart1,easing:this.fadeInEffect,queue:false,complete:function(){that.$itemOverview.animate({opacity:1},{duration:fadePart2,easing:that.fadeOutEffect,queue:false});}});this.$itemOverview.animate({marginLeft:this.actualMargin},{duration:timing,easing:this.slideEffect});this.actualPosition=newPosition;if(this.autoSliderStop){this.autoSliderCounter=newPosition;}}};$(document).ready(function(){new CalendarSlider();});function CalendarSlider(){var calendarSliderInstance=this;this.$timelineSliderContainer=$('#calendarWrapper .cal');if(this.$timelineSliderContainer.length>0){this.$timelineSliderNextButton=$('#calendarNext');this.$timelineSliderPrevButton=$('#calendarPrev');this.timelineSliderWidth=$('#calendarWrapper').width();this.timelineSliderWidthFull=this.$timelineSliderContainer.children().length*this.timelineSliderWidth;this.$timelineSliderContainer.width(this.timelineSliderWidthFull);this.timelineSliderMaxSlide=-(this.timelineSliderWidthFull-this.timelineSliderWidth);this.$monthSliderContainer=$('#calendarMonths ul');this.$monthSliderItems=this.$monthSliderContainer.children();this.$monthSliderContainer.height(this.$monthSliderContainer.children().length*24);this.$monthSliderLoadingIndicator=$('#calendarMonths .loading');this.$firstMonth=this.$monthSliderContainer.children().first();this.timelineSliderCurrentMargin=0;this.timelineSliderCurrentItem=0;this.monthSliderCurrentMargin=0;this.monthSliderCurrentItem=0;this.monthToLoad=this.$firstMonth.next().next();this.$lastTooltip=null;this.timelineSliderIsAnimating=null;this.isLoading='false';this.$firstMonth.attr('data-month-downloaded','true');this.$firstMonth.next().attr('data-month-downloaded','true');$(this.$timelineSliderContainer.children()[0]).prepend('<li class="first"><div class="day"></div></li>');var firstList=$(this.$timelineSliderContainer.children()[0]);var length=firstList.children().length;$(firstList.children()[length-1]).addClass('last').empty();$(this.$timelineSliderContainer.children()[1]).css('visibility','hidden');var lists=$(this.$timelineSliderContainer.children());$.each(lists,function(){$($(this).children()[0]).addClass('firstItem');});$('body').append('<ul id="tooltipContainer"></ul>');this.$tooltipContainer=$('#tooltipContainer');if(!$('body.lt-ie9').length){this.boxCalConnect();}
this.divideToLeftRightSide();this.$timelineSliderNextButton.on('click',function(e){calendarSliderInstance.slideRight(e,calendarSliderInstance);});this.$timelineSliderPrevButton.on('click',function(e){calendarSliderInstance.slideLeft(e,calendarSliderInstance);});this.$monthSliderItems.on('click',function(e){calendarSliderInstance.monthHandler(e,calendarSliderInstance);});$('#calendarWrapper .cal ul li').on('mouseenter',function(e){calendarSliderInstance.showTooltip(e,calendarSliderInstance);});this.$timelineSliderContainer.css('display','block');}}
CalendarSlider.prototype.monthHandler=function(e,calendarSliderInstance){if(this.monthSliderCurrentItem<calendarSliderInstance.$monthSliderItems.index($(e.target))){calendarSliderInstance.slideRight(e,calendarSliderInstance);calendarSliderInstance.$monthSliderLoadingIndicator.show();}
else{calendarSliderInstance.slideLeft(e,calendarSliderInstance);}};CalendarSlider.prototype.adjustSlider=function(calendarSliderInstance){calendarSliderInstance.$timelineSliderNextButton.addClass('loading');if(calendarSliderInstance.isLoading==='false'){calendarSliderInstance.isLoading='true';$.ajax({type:'GET',timeout:8000,dataType:'html',url:calendarSliderInstance.monthToLoad.attr('data-link')}).done(function(html){calendarSliderInstance.monthToLoad.attr('data-month-downloaded','true');calendarSliderInstance.monthToLoad=calendarSliderInstance.monthToLoad.next();calendarSliderInstance.timelineSliderWidthFull+=calendarSliderInstance.timelineSliderWidth;calendarSliderInstance.$timelineSliderContainer.width(calendarSliderInstance.timelineSliderWidthFull);calendarSliderInstance.timelineSliderMaxSlide=-(calendarSliderInstance.timelineSliderWidthFull-calendarSliderInstance.timelineSliderWidth);calendarSliderInstance.$timelineSliderContainer.append(html).css('visibility','hidden');calendarSliderInstance.divideToLeftRightSide();calendarSliderInstance.$timelineSliderNextButton.removeClass('loading');calendarSliderInstance.$monthSliderLoadingIndicator.hide();$('#calendarWrapper .cal ul li').on('mouseenter',function(e){calendarSliderInstance.showTooltip(e,calendarSliderInstance);});calendarSliderInstance.isLoading='false';});}};CalendarSlider.prototype.slideRight=function(e,calendarSliderInstance){if(calendarSliderInstance.monthToLoad.length&&calendarSliderInstance.monthToLoad.attr('data-month-downloaded')==='false'){calendarSliderInstance.adjustSlider(calendarSliderInstance);}else{if(calendarSliderInstance.monthToLoad.index(calendarSliderInstance.$monthSliderItems.length)){calendarSliderInstance.$timelineSliderNextButton.animate({opacity:'0'});calendarSliderInstance.$monthSliderLoadingIndicator.remove();}}
if(calendarSliderInstance.$tooltipContainer.children().length){calendarSliderInstance.$tooltipContainer.removeClass('right').empty();}
if(calendarSliderInstance.timelineSliderCurrentMargin==calendarSliderInstance.timelineSliderMaxSlide){}
else{if(calendarSliderInstance.timelineSliderIsAnimating){}
else{calendarSliderInstance.timelineSliderIsAnimating=1;calendarSliderInstance.timelineSliderCurrentMargin-=calendarSliderInstance.timelineSliderWidth;calendarSliderInstance.$timelineSliderPrevButton.animate({opacity:'1'});calendarSliderInstance.monthSliderCurrentMargin-=30;$(calendarSliderInstance.$timelineSliderContainer.children()).css('visibility','visible');$(calendarSliderInstance.$timelineSliderContainer.children()[calendarSliderInstance.timelineSliderCurrentItem+2]).css('visibility','hidden');calendarSliderInstance.$monthSliderContainer.animate({marginTop:calendarSliderInstance.monthSliderCurrentMargin},function(){$(calendarSliderInstance.$timelineSliderContainer.children()[calendarSliderInstance.timelineSliderCurrentItem]).css('visibility','hidden');calendarSliderInstance.timelineSliderCurrentItem++;calendarSliderInstance.timelineSliderIsAnimating=null;});calendarSliderInstance.monthSliderCurrentItem++;calendarSliderInstance.$monthSliderItems.not($(calendarSliderInstance.$monthSliderItems[calendarSliderInstance.monthSliderCurrentItem])).animate({opacity:0.4});$(calendarSliderInstance.$monthSliderItems[calendarSliderInstance.monthSliderCurrentItem]).animate({opacity:1});$('#calendarWrapper .content_100').animate({marginLeft:calendarSliderInstance.timelineSliderCurrentMargin});}}};CalendarSlider.prototype.slideLeft=function(e,calendarSliderInstance){if(calendarSliderInstance.$tooltipContainer.children().length){calendarSliderInstance.$tooltipContainer.removeClass('right').empty();}
if(calendarSliderInstance.timelineSliderCurrentMargin==0){}
else{if(calendarSliderInstance.timelineSliderIsAnimating){}
else{calendarSliderInstance.timelineSliderIsAnimating=1;calendarSliderInstance.timelineSliderCurrentMargin+=calendarSliderInstance.timelineSliderWidth;if(calendarSliderInstance.timelineSliderCurrentMargin==0){calendarSliderInstance.$timelineSliderPrevButton.animate({opacity:'0'});}
calendarSliderInstance.$timelineSliderNextButton.animate({opacity:'1'});calendarSliderInstance.monthSliderCurrentMargin+=30;$(calendarSliderInstance.$timelineSliderContainer.children()).css('visibility','visible');$(calendarSliderInstance.$timelineSliderContainer.children()[calendarSliderInstance.timelineSliderCurrentItem-2]).css('visibility','hidden');calendarSliderInstance.$monthSliderContainer.animate({marginTop:calendarSliderInstance.monthSliderCurrentMargin},function(){$(calendarSliderInstance.$timelineSliderContainer.children()[calendarSliderInstance.timelineSliderCurrentItem]).css('visibility','hidden');calendarSliderInstance.timelineSliderCurrentItem--;calendarSliderInstance.timelineSliderIsAnimating=null;});calendarSliderInstance.monthSliderCurrentItem--;calendarSliderInstance.$monthSliderItems.not($(calendarSliderInstance.$monthSliderItems[calendarSliderInstance.monthSliderCurrentItem])).animate({opacity:.4});$(calendarSliderInstance.$monthSliderItems[calendarSliderInstance.monthSliderCurrentItem]).animate({opacity:1});$('#calendarWrapper .content_100').animate({marginLeft:calendarSliderInstance.timelineSliderCurrentMargin});}}};CalendarSlider.prototype.showTooltip=function(e,calendarSliderInstance){var $hoveredElement=$(e.target);var $tooltip=null;var side=null;if($(e.target).parent().is('li')){$tooltip=$hoveredElement.parent().find('.calendarTooltip');}
else{$tooltip=$hoveredElement.find('.calendarTooltip');}
if($tooltip.length<1){}else{if($tooltip.parent().hasClass('right')){side='right';}
var tooltipDeepCopy=$tooltip.parent().clone();}
if(calendarSliderInstance.$lastTooltip!=null&&calendarSliderInstance.$lastTooltip[0]==$tooltip[0]){calendarSliderInstance.$lastTooltip=null;}
else{if(calendarSliderInstance.$lastTooltip!=null){$(this).css('display','none');calendarSliderInstance.$tooltipContainer.removeClass('right').empty();}
calendarSliderInstance.$lastTooltip=$tooltip;if($tooltip.length<1){calendarSliderInstance.$tooltipContainer.removeClass('right').empty();}
else{var offset=$tooltip.parent().offset();if(calendarSliderInstance.$tooltipContainer.children().length<1){calendarSliderInstance.$tooltipContainer.addClass(side).append(tooltipDeepCopy).find('li').offset({top:offset.top,left:offset.left}).css('display','block');}
else{calendarSliderInstance.$tooltipContainer.removeClass('right').empty();calendarSliderInstance.$tooltipContainer.addClass(side).append(tooltipDeepCopy).find('li').offset({top:offset.top,left:offset.left}).css('display','block');}}
$('#tooltipContainer li').on('mouseleave',function(){calendarSliderInstance.$tooltipContainer.removeClass('right').empty();});$('#tooltipContainer li').on('click',function(){if(calendarSliderInstance.$tooltipContainer.children().length>0){calendarSliderInstance.$tooltipContainer.removeClass('right').empty();}});}};CalendarSlider.prototype.divideToLeftRightSide=function(){var lists=$('#calendarWrapper .cal ul');$.each(lists,function(){if($(this).attr('data-sorted')!=='true'){var items=$(this).children('li');var itemCount=items.length;var itemParts=itemCount/2;var itemsAsArray=$.makeArray(items);for(var i=0;i<Math.round(itemParts);i++){$(itemsAsArray[i]).addClass('left');}
for(i=Math.round(itemParts);i<itemCount;i++){$(itemsAsArray[i]).addClass('right');}
$(this).attr('data-sorted','true');}});};CalendarSlider.prototype.boxCalConnect=function(){var regEx=/^\d{4}\-\d{2}\-\d{2}-\d{2}-\d{2}$/;var $elements=$('.tickets').children();$.each($elements,function(){var classes=$(this).attr('class').split(/\s+/);$.each(classes,function(){if(regEx.test(this)){var that=this;$('.'+this).hover(function(){$('.'+that).addClass('hoverConnect');},function(){$('.'+that).removeClass('hoverConnect');});}});});};!function($){var SolrAutosuggest=function(){var that=this;this.$searchForm=$('#solrSearch');this.$formInput=$('#solrSearchInput');this.$suggestionsWrapper=$('#suggestionsWrapper');this.searchFormAction=this.$searchForm.attr('action');this.activeElementPosition=0;this.$formInput.on('input',function(){that.suggest(that);});this.$formInput.on('keydown',function(e){if(e.keyCode=='38'){that.selectSuggestion(-1);}
else if(e.keyCode=='40'){that.selectSuggestion(1);}
else if(e.keyCode=='27'){e.preventDefault();}
else{that.activeElementPosition=0;}});$('body').on('click',function(e){if($(e.target).attr('id')!=='suggestionsWrapper'||!$(e.target).parents('#suggestionsWrapper').length){that.$suggestionsWrapper.hide();}});$(document).keyup(function(e){if(e.keyCode=='27'){that.$suggestionsWrapper.hide();}});};SolrAutosuggest.prototype={selectSuggestion:function(direction){var $currentSuggestionList=this.$suggestionsWrapper.find('li'),$activeElement;if($currentSuggestionList.length&&this.activeElementPosition<$currentSuggestionList.length||direction<1){this.activeElementPosition+=direction;if(this.activeElementPosition<1){this.activeElementPosition=1;}
$activeElement=$($currentSuggestionList[this.activeElementPosition-1]);this.$formInput.attr('value',$activeElement.text());$currentSuggestionList.removeClass('active');$activeElement.addClass('active');}},suggest:function(that){var autoSuggestUrl=this.searchFormAction+'?suggest='+this.$formInput.val()+'&no_cache=1';$.ajax({type:'GET',timeout:4000,dataType:'json',url:autoSuggestUrl,success:function(rsp){console.log(autoSuggestUrl);console.log(rsp);if(rsp.length){that.$suggestionsWrapper.show();var suggestions='<ul>';for(var i=0;i<rsp.length;i++){suggestions+='<li><a href="'+that.searchFormAction+'?no_cache=1&q='+rsp[i]+'">'+rsp[i]+'</a></li>';}
suggestions+='</ul>';that.$suggestionsWrapper.html(suggestions).show();}
else{that.$suggestionsWrapper.hide();}},error:function(rsp){that.$suggestionsWrapper.hide();console.log('error with autosuggest');console.log(autoSuggestUrl);console.log(rsp);}});}};$.fn.solrAutosuggest=function(){return new SolrAutosuggest();};$.fn.solrAutosuggest.Constructor=SolrAutosuggest;}(window.jQuery);$(document).ready(function(){if($('#solrSearch').length){$('#solrSearch').solrAutosuggest();}});var bphilNS=bphilNS||{};$(document).ready(function(){"use strict";if($('#liveticker').length>0){bphilNS.NextliveCountdown={upcomingDchConcertUrl:'typo3conf/ext/bph_concertxml/getUpcomingDCH.php',countdownDelta:null,dchId:null,runningTimer:null,beenInTickerLoop:false,countdownElement:$('#liveticker'),countdownDaysValueElement:$('#liveticker-days-value'),countdownHoursValueElement:$('#liveticker-hours-value'),countdownMinutesValueElement:$('#liveticker-minutes-value'),countdownSecondsValueElement:$('#liveticker-seconds-value'),showCountdown:function(){this.countdownElement.removeClass('hidden');},updateCountdown:function(){this.countdownDelta--;if(this.countdownDelta<=0){this.countdownElement.remove();$('#liveticker-nowlive').removeClass('display-none');bphilNS.NextliveCountdown=null;if(this.dchId){var siteurl=location.pathname;var sitelanguage=siteurl.split('/');if(sitelanguage[1]==="en"||sitelanguage[0]==="en"){$('#liveticker-linktodch').attr('href','http://www.digitalconcerthall.com/en/concert/'+this.dchId+'/');}else{$('#liveticker-linktodch').attr('href','http://www.digitalconcerthall.com/de/konzert/'+this.dchId+'/');}}
return;}else{var tage=Math.floor(this.countdownDelta/86400);var stunden=Math.floor((this.countdownDelta-(tage*86400))/3600);var minuten=Math.floor((this.countdownDelta-(tage*86400+stunden*3600))/60);var sekunden=this.countdownDelta%60;this.countdownDaysValueElement.html(tage);this.countdownHoursValueElement.html(stunden);this.countdownMinutesValueElement.html(minuten);this.countdownSecondsValueElement.html(sekunden);}
this.runningTimer=setTimeout('bphilNS.NextliveCountdown.updateCountdown()',1000);}};$.getJSON(bphilNS.NextliveCountdown.upcomingDchConcertUrl,function(data,status){if(data.dch_id){bphilNS.NextliveCountdown.dchId=data.dch_id;}
bphilNS.NextliveCountdown.countdownDelta=data.delta-1800;bphilNS.NextliveCountdown.showCountdown();bphilNS.NextliveCountdown.updateCountdown();});}});$(document).ready(function(){"use strict";$('#print').on('click',function(e){window.print();return false;});if($('html.ie9').length===0&&$('html.lt-ie9').length===0){var jsLinkBubbleElements=$('.jsLinkBubble').find('a');for(var i=0,jsLInkBubbleElementsLength=jsLinkBubbleElements.length;i<jsLInkBubbleElementsLength;i++){var currentJsLinkBubbleElement=$(jsLinkBubbleElements[i]);if(currentJsLinkBubbleElement.attr('target')!==undefined&&currentJsLinkBubbleElement.attr('target')!=='_self'){currentJsLinkBubbleElement.closest('.jsLinkBubble').addClass('hasJsLinkBubbleExternalLink').append('<a class="jsLinkBubbleExternalLink" href="'+currentJsLinkBubbleElement.attr('href')+'" target="'+currentJsLinkBubbleElement.attr('target')+'"></a>');}}}
$('body').on('click','.jsLinkBubble',function(event){var linkElement=$(this).find('a').eq(0);var linkToGo=linkElement.attr("href");if(typeof linkToGo==='undefined'){return true;}
if($('html.ie9').length===0&&$('html.lt-ie9').length===0){if((linkElement.attr('target')!==undefined&&linkElement.attr('target')!=='_self')){return true;}}
if(linkToGo.split(':')[0]==='http'||linkToGo.split(':')[0]==='https'){window.location.href=linkToGo;}else if(linkToGo.split(':')[0]==='https'){window.location.href="https://"+window.location.host+"/"+linkToGo;}
else{window.location.href="http://"+window.location.host+"/"+linkToGo;}
event.preventDefault();event.stopPropagation();});});var BP=BP||{};(function(){"use strict";BP.GridIdentHeight=(function(BP,$){var SELECTOR_PARENT_CLASS='jsGridIdentHeight',DATA_NAME_ADJUSTED='jsGridIdentHeightAdjusted',DATA_NAME_ORIGINALHEIGHT='jsGridIdentHeightOriginalHeight',adjustHeightOfChildren=function($parentElement){var children=$parentElement.children;var childrenLength=children.length;var i=0,maxHeight=0,currentChildHeight=0,lastChildHeight=0,adjustmentNeeded=false;for(i=0;i<childrenLength;i++){currentChildHeight=$(children[i]).height();if(currentChildHeight>maxHeight){maxHeight=currentChildHeight;}
if(lastChildHeight!==0&&currentChildHeight!==lastChildHeight){adjustmentNeeded=true;}
lastChildHeight=currentChildHeight;}
if(adjustmentNeeded){for(i=0;i<childrenLength;i++){if(!$.data(children[i],DATA_NAME_ADJUSTED)&&children[i].style.height!=='auto'){$.data(children[i],DATA_NAME_ORIGINALHEIGHT,children[i].style.height);}
$(children[i]).height(maxHeight);$.data(children[i],DATA_NAME_ADJUSTED,true);}}},setHeight=function($parentElement,options){var $parentElements;if($parentElement.hasClass(SELECTOR_PARENT_CLASS)){$parentElements=$parentElement;}else{$parentElements=$parentElement.find('.'+SELECTOR_PARENT_CLASS);}
for(var i=0,parentElementsLength=$parentElements.length;i<parentElementsLength;i++){adjustHeightOfChildren($parentElements[i]);if(options!==undefined&&options.hasOwnProperty('setOnlyOnce')&&options.setOnlyOnce===true){$($parentElements[i]).removeClass(SELECTOR_PARENT_CLASS);}}},updateHeight=function($parentElement,options){resetHeight($parentElement);setHeight($parentElement,options);},resetHeight=function($parentElement){var $parentElements;if($parentElement.hasClass(SELECTOR_PARENT_CLASS)){$parentElements=$parentElement;}else{$parentElements=$parentElement.find('.'+SELECTOR_PARENT_CLASS);}
var $children=$parentElements.children();for(var i=0,childrenLength=$children.length;i<childrenLength;i++){if($children[i].style.height!=='auto'){if($.data($children[i],DATA_NAME_ORIGINALHEIGHT)){$children[i].style.height=$.data($children[i],DATA_NAME_ORIGINALHEIGHT);}else{$children[i].style.height='auto';}}
if($.data($children[i],DATA_NAME_ADJUSTED)){$.data($children[i],DATA_NAME_ADJUSTED,null);}}};return{setHeight:setHeight,resetHeight:resetHeight,updateHeight:updateHeight};}(BP,jQuery));}());$(document).ready(function(){"use strict";BP.GridIdentHeight.setHeight(BP.DomElementCache.get('body'));});function write_language_cookie(lang)
{var date=new Date();date.setTime(date.getTime()+(365*24*60*60*1000));document.cookie='lang='+lang+'; expires='+date.toGMTString()+';path=/;';}
var BP=BP||{};(function(){"use strict";BP.CalendarBookmark=(function(BP){var COOKIE_NAME='bookmarkedPerformances',COOKIE_EXPIRES=999,SELECTOR_META_NAVIGATION_ITEM='#jsCalendarBookmarkGloballinkListitem',SELECTOR_BOOKMARK_TRIGGER='#jsCalendarBookmark',SELECTOR_CALENDAR_FILTER='#calendarFilter',SELECTOR_BOOKMARK_FILTER='#jsCalendarBookmarkFilter',SELECTOR_BOOKMARK_TOOLTIP='#jsCalendarBookmarkTooltip',CSSCLASS_MARKED='marked',URL_PARAM_PERFORMANCES='performances',isOnShowByIdPage=false,isOnPerformanceCalendarViewPage=false,isCurrentDetailpageBookmarked,bookmarkedCookieContent,bookmarkedPerformances,currentpagePerformances,globalLinkListitemElement,globalLinkElement,globalLinkInitialUrl,updateGlobalLinkElement=function(){if(globalLinkElement===undefined){initForEveryView();}
var globalLinkUrl=globalLinkInitialUrl;if(bookmarkedPerformances===undefined||bookmarkedPerformances.length===0){globalLinkElement.attr('href',globalLinkUrl);globalLinkListitemElement.hide();}else{globalLinkUrl+='&'+URL_PARAM_PERFORMANCES+'='+bookmarkedPerformances.join(",");globalLinkElement.attr('href',globalLinkUrl);globalLinkListitemElement.show();}},initForEveryView=function(){globalLinkListitemElement=BP.DomElementCache.get(SELECTOR_META_NAVIGATION_ITEM);globalLinkElement=globalLinkListitemElement.find('a').first();globalLinkInitialUrl=globalLinkElement.attr('href');updateGlobalLinkElement();},initForPerformanceCalendarView=function(){var bookmarkFilterLink=BP.DomElementCache.get(SELECTOR_BOOKMARK_FILTER);if(bookmarkFilterLink.length===0){return false;}
if(bookmarkedPerformances===undefined){bookmarkFilterLink.parent().remove();}else{var staticLink=bookmarkFilterLink.attr('href');var paramIntro='?';if(staticLink.indexOf('?')>=0){paramIntro='&';}
bookmarkFilterLink.attr('href',staticLink+paramIntro+URL_PARAM_PERFORMANCES+'='+bookmarkedPerformances.join(","));}},initForShowById=function(){if(isBookmarkOnCurrentpage()){BP.DomElementCache.get(SELECTOR_BOOKMARK_TRIGGER).addClass(CSSCLASS_MARKED).on('click',removeBookmarkButtonHandler);}else{BP.DomElementCache.get(SELECTOR_BOOKMARK_TRIGGER).on('click',addBookmarkButtonHandler);}},readBookmarkedPerformances=function(){bookmarkedCookieContent=jQuery.cookie(COOKIE_NAME);if(bookmarkedCookieContent!==null&&bookmarkedCookieContent.length>0){bookmarkedPerformances=[];bookmarkedPerformances=bookmarkedCookieContent.split(',');}},readCurrentpagePerformances=function(){BP.DomElementCache.set('div.calEntryPerformance',$('section.calEntry.detailed').eq(0).find('div.calEntryPerformance[data-uid]'));var performances=BP.DomElementCache.get('div.calEntryPerformance');if(performances===null||performances.length>0){currentpagePerformances=[];for(var i=0,performancesLength=performances.length;i<performancesLength;i++){currentpagePerformances.push(performances[i].getAttribute('data-uid'));}}},isBookmarkOnCurrentpage=function(){if(isCurrentDetailpageBookmarked!==undefined){return isCurrentDetailpageBookmarked;}
if(jQuery.cookie(COOKIE_NAME)===null){isCurrentDetailpageBookmarked=false;return isCurrentDetailpageBookmarked;}
if(bookmarkedPerformances===undefined){readBookmarkedPerformances();}
if(currentpagePerformances===undefined){readCurrentpagePerformances();}
if(typeof BP.Utils==='undefined'||typeof BP.Utils.getIntersectionOfArrays==='undefined'){var _gaq=window._gaq||[];_gaq.push(['_trackEvent','Error','JS Module Error','BP.Utils.getIntersectionOfArrays not available.']);return false;}
var bookmarksOnCurrentPage=BP.Utils.getIntersectionOfArrays(currentpagePerformances,bookmarkedPerformances);if(bookmarksOnCurrentPage.length===0){isCurrentDetailpageBookmarked=false;}else{isCurrentDetailpageBookmarked=true;}
return isCurrentDetailpageBookmarked;},addCurrentpagePerformancesToBookmarkedPerformances=function(event){if(bookmarkedPerformances===undefined){readBookmarkedPerformances();}
if(bookmarkedPerformances===undefined){bookmarkedPerformances=[];}
if(currentpagePerformances===undefined){readCurrentpagePerformances();}
for(var i=0;i<currentpagePerformances.length;i++){if(bookmarkedPerformances.indexOf(currentpagePerformances[i])===-1){bookmarkedPerformances.push(currentpagePerformances);}}
saveBookmarkedPerformancesToCookie();},removeCurrentpagePerformancesFromBookmarkedPerformances=function(event){if(bookmarkedPerformances===undefined){readBookmarkedPerformances();}
if(bookmarkedPerformances===undefined){return false;}
if(currentpagePerformances===undefined){readCurrentpagePerformances();}
for(var i=0;i<currentpagePerformances.length;i++){if(bookmarkedPerformances.indexOf(currentpagePerformances[i])>=0){bookmarkedPerformances.splice(bookmarkedPerformances.indexOf(currentpagePerformances[i]),1);}}
saveBookmarkedPerformancesToCookie();},saveBookmarkedPerformancesToCookie=function(){if(bookmarkedPerformances===undefined||bookmarkedPerformances.length===0){bookmarkedCookieContent='';jQuery.cookie(COOKIE_NAME,null,{expires:COOKIE_EXPIRES,path:'/'});}else{bookmarkedCookieContent=bookmarkedPerformances.join(",");jQuery.cookie(COOKIE_NAME,bookmarkedCookieContent,{expires:COOKIE_EXPIRES,path:'/'});}},addBookmarkButtonHandler=function(event){event.preventDefault();addCurrentpagePerformancesToBookmarkedPerformances();BP.DomElementCache.get(SELECTOR_BOOKMARK_TRIGGER).addClass(CSSCLASS_MARKED).off('click',addBookmarkButtonHandler).on('click',removeBookmarkButtonHandler);BP.DomElementCache.get(SELECTOR_BOOKMARK_TOOLTIP).show();window.scrollTo(0,0);updateGlobalLinkElement();var _gaq=window._gaq||[];_gaq.push(['_trackEvent','CalendarBookmark','addBookmark']);},removeBookmarkButtonHandler=function(event){event.preventDefault();removeCurrentpagePerformancesFromBookmarkedPerformances();BP.DomElementCache.get(SELECTOR_BOOKMARK_TRIGGER).removeClass(CSSCLASS_MARKED).off('click',removeBookmarkButtonHandler).on('click',addBookmarkButtonHandler);updateGlobalLinkElement();var _gaq=window._gaq||[];_gaq.push(['_trackEvent','CalendarBookmark','removeBookmark']);},checkCalendarBookmarkOccurence=function(){if(BP.DomElementCache.get(SELECTOR_BOOKMARK_TRIGGER).length>0){isOnShowByIdPage=true;}
if(BP.DomElementCache.get(SELECTOR_CALENDAR_FILTER).length>0){isOnPerformanceCalendarViewPage=true;}
return(isOnShowByIdPage||isOnPerformanceCalendarViewPage);},init=function(){readBookmarkedPerformances();initForEveryView();checkCalendarBookmarkOccurence();if(isOnPerformanceCalendarViewPage){initForPerformanceCalendarView();}
if(isOnShowByIdPage){initForShowById();}
return true;};return{init:init};}(BP));}());$(document).ready(function(){BP.CalendarBookmark.init();});
/*! footer-newsletterform.js */
$(document).ready(function(){$('#footer-newsletterform').bind('submit',function(e){var reg=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;var address='';if($('#akyjt-akyjt').length){address=$('#akyjt-akyjt').val();}else if($("#aithy-aithy").length){address=$('#aithy-aithy').val();}
if(reg.test(address)===false){$('#footer-newsletterform-error').removeClass('display-none');e.preventDefault();return false;}
return true;});});var BP=BP||{};BP.getNavigationTimingStats=function(){"use strict";var timing=window.performance.timing;return{dns:timing.domainLookupEnd-timing.domainLookupStart,connect:timing.connectEnd-timing.connectStart,ttfb:timing.responseStart-timing.connectEnd,basePage:timing.responseEnd-timing.responseStart,frontEnd:timing.loadEventStart-timing.responseEnd};};window.onload=function(){"use strict";if(window.performance&&window.performance.timing){var _gaq=window._gaq||[];var ntStats=BP.getNavigationTimingStats();if(ntStats.dns>0&&ntStats.dns<60000){_gaq.push(['_trackTiming','Navigation Timing','DNS',ntStats.dns]);}
if(ntStats.connect>0&&ntStats.connect<60000){_gaq.push(['_trackTiming','Navigation Timing','Connect',ntStats.connect]);}
if(ntStats.ttfb>0&&ntStats.ttfb<60000){_gaq.push(['_trackTiming','Navigation Timing','TTFB',ntStats.ttfb]);}
if(ntStats.basePage>0&&ntStats.basePage<60000){_gaq.push(['_trackTiming','Navigation Timing','BasePage',ntStats.basePage]);}
if(ntStats.frontEnd>0&&ntStats.frontEnd<60000){_gaq.push(['_trackTiming','Navigation Timing','FrontEnd',ntStats.frontEnd]);}}};function webkitBrowser(){return Modernizr.cssreflections;}
$(document).ready(function(){$('#searchForm .submit').click(function(e){if($('#searchField').val()=='Suche'||$('#searchField').val()=='Search'){$('#searchField').val('');}
return true;});$('#calendar_filter select').change(function()
{var concertLabel=this.value;$('.vevent').removeClass('disabled_event');$('td').removeClass('disabled_day');$('.highlighted_event').removeClass('highlighted_event');$('.'+concertLabel).addClass('highlighted_event');$('.vevent:not(.highlighted_event)').addClass('disabled_event');$('td:not(:has(.highlighted_event))').addClass('disabled_day');});var leftOffset=-90;var triggerCount=$('a.trigger').length;if(triggerCount>0)
{$('a.trigger').cluetip({width:300,tracking:true,local:true,arrows:true,dropShadow:true,dropShadowSteps:2,leftOffset:leftOffset,fx:{open:'toggle',openSpeed:0},showTitle:false,titleAttribute:'',hideLocal:true,hoverIntent:{sensitivity:1,interval:0,timeout:0}});}
$('.dch_link_box').click(function()
{window.open('http://www.digitalconcerthall.com/','_blank');});$('.row-special-teaser h2').each(function(i){if(this.innerHTML=='')this.className='empty';});$('.row-special-teaser h2.empty').parent().parent().hide();});function getWindowInnerWidth(){if(window.innerWidth){return window.innerWidth;}else if(document.documentElement&&document.documentElement.clientWidth){return document.documentElement.clientWidth;}else if(document.body&&document.body.clientWidth){return document.body.clientWidth;}else{return 0;}}
function getWindowInnerHeight(){if(window.innerHeight){return window.innerHeight;}else if(document.documentElement&&document.documentElement.clientHeight){return document.documentElement.clientHeight;}else if(document.body&&document.body.clientHeight){return document.body.clientHeight;}else{return 0;}}
function adaptToScreen(){var windowInnerHeight=getWindowInnerHeight();var windowInnerWidth=getWindowInnerWidth();if(windowInnerWidth<1060){$('body').addClass('screen-1024');}else{$('body').removeClass('screen-1024');}}
$(document).ready(function(){adaptToScreen();blockBox();});$(window).resize(function(){adaptToScreen();});function blockBox(){$('.tx-bphprojects-previewmanual .image-above').addClass('blockBox').click(function(){location.href=window.location.protocol+'//'+window.location.host+'/'+$('h3 a',$(this)).attr('href')});$('#concertpreview-box .row').addClass('blockBox').click(function(){location.href=window.location.protocol+'//'+window.location.host+'/'+$('h2 a',$(this)).attr('href')});$('.row-special-teaser').addClass('blockBox').click(function(){var isExternalLink=$('h2 a',$(this)).attr('target');if(isExternalLink=='_blank'){var extLink=$('h2 a',$(this)).attr('href');window.open(extLink,'_blank');return false;}else{location.href=window.location.protocol+'//'+window.location.host+'/'+$('h2 a',$(this)).attr('href')}});}
$(document).ready(function(){$('div.choice','#nav-lang').hide();$('div.title','#nav-lang').click(function(){$('#nav-lang').toggleClass("opened");$("div.choice",'#nav-lang').toggle();});});